### ISSUE TITLE
docker build fail

### ISSUE THREAD

**Issue by yamazakei321** [odavid/jenkins-jnlp-slave#12] opened 2019-09-26 14:48 UTC
Removing intermediate container 1ad07e89244c
 ---> 215c07096e75
Step 15/25 : RUN     if [ -f /etc/alpine-release ] ; then         cd /tmp                 && ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk"         && ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk"         && ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk"         && apk add --no-cache --virtual=.build-dependencies wget curl ca-certificates binutils gnupg         && echo             "-----BEGIN PUBLIC KEY-----            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApZ2u1KJKUu/fW4A25y9m            y70AGEa/J3Wi5ibNVGNn1gT1r0VfgeWd0pUybS4UmcHdiNzxJPgoWQhV2SSW1JYu            tOqKZF5QSN6X937PTUpNBjUvLtTQ1ve1fp39uf/lEXPpFpOPL88LKnDBgbh7wkCp            m2KzLVGChf83MS0ShL6G9EQIAUxLm99VpgRjwqTQ/KfzGtpke1wqws4au0Ab4qPY            KXvMLSPLUp7cfulWvhmZSegr5AdhNw5KNizPqCJT8ZrGvgHypXyiFvvAH5YRtSsc            Zvo9GI2e2MaZyo9/lvb+LbLEJZKEQckqRj4P26gmASrZEPStwc+yqy1ShHLA0j6m            1QIDAQAB            -----END PUBLIC KEY-----" | sed 's/   */\n/g' > "/etc/apk/keys/sgerrand.rsa.pub"         && wget -q             "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"             "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"             "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"         && apk add --no-cache             "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"             "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"             "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"                 && rm "/etc/apk/keys/sgerrand.rsa.pub"                 && wget -q ${GCC_LIBS_URL} ${GCC_LIBS_URL}.sig         && mkdir /tmp/gcc         && tar -xf "${GCC_LIBS}" -C /tmp/gcc         && mv /tmp/gcc/usr/lib/libgcc* /tmp/gcc/usr/lib/libstdc++* /usr/glibc-compat/lib         && strip /usr/glibc-compat/lib/libgcc_s.so.* /usr/glibc-compat/lib/libstdc++.so*         && mkdir /tmp/libz         && wget -q "${ZLIB_URL}" "${ZLIB_URL}.sig"         && tar -xf "${ZLIB}" -C /tmp/libz         && mv /tmp/libz/usr/lib/libz.so* /usr/glibc-compat/lib         &&         /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8         && echo "export LANG=en_US.UTF-8" > /etc/profile.d/locale.sh                 && apk del glibc-i18n                 && apk del .build-dependencies         && rm             "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"             "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"             "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"                 && rm -rf /tmp/${GLIBC_VER}.apk /tmp/gcc /tmp/${ZLIB} /tmp/libz /tmp/${GCC_LIBS} /var/cache/apk/*         ;     elif [ -f /etc/debian_version ] ; then         echo "Debian, setting locales"         && apt-get update         && apt-get install -y --no-install-recommends locales         && localedef  -i en_US -f UTF-8 en_US.UTF-8         && rm -rf /var/lib/apt/lists/*         ;     fi
 ---> Running in bf09921bc4a5
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/19) Installing wget (1.20.3-r0)
(2/19) Installing curl (7.64.0-r3)
(3/19) Installing binutils (2.31.1-r2)
(4/19) Installing libgpg-error (1.33-r0)
(5/19) Installing libassuan (2.5.1-r0)
(6/19) Installing libcap (2.26-r0)
(7/19) Installing pinentry (1.1.0-r0)
Executing pinentry-1.1.0-r0.post-install
(8/19) Installing libgcrypt (1.8.4-r1)
(9/19) Installing gmp (6.1.2-r1)
(10/19) Installing nettle (3.4.1-r0)
(11/19) Installing libunistring (0.9.10-r0)
(12/19) Installing gnutls (3.6.7-r0)
(13/19) Installing libksba (1.3.5-r0)
(14/19) Installing db (5.3.28-r1)
(15/19) Installing libsasl (2.1.27-r1)
(16/19) Installing libldap (2.4.48-r0)
(17/19) Installing npth (1.6-r0)
(18/19) Installing gnupg (2.2.12-r0)
(19/19) Installing .build-dependencies (0)
Executing busybox-1.29.3-r10.trigger
OK: 165 MiB in 92 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/3) Installing glibc (2.29-r0)
(2/3) Installing glibc-bin (2.29-r0)
(3/3) Installing glibc-i18n (2.29-r0)
Executing glibc-bin-2.29-r0.trigger
OK: 197 MiB in 95 packages
The command '/bin/sh -c if [ -f /etc/alpine-release ] ; then         cd /tmp                 && ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk"         && ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk"         && ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk"         && apk add --no-cache --virtual=.build-dependencies wget curl ca-certificates binutils gnupg         && echo             "-----BEGIN PUBLIC KEY-----            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApZ2u1KJKUu/fW4A25y9m            y70AGEa/J3Wi5ibNVGNn1gT1r0VfgeWd0pUybS4UmcHdiNzxJPgoWQhV2SSW1JYu            tOqKZF5QSN6X937PTUpNBjUvLtTQ1ve1fp39uf/lEXPpFpOPL88LKnDBgbh7wkCp            m2KzLVGChf83MS0ShL6G9EQIAUxLm99VpgRjwqTQ/KfzGtpke1wqws4au0Ab4qPY            KXvMLSPLUp7cfulWvhmZSegr5AdhNw5KNizPqCJT8ZrGvgHypXyiFvvAH5YRtSsc            Zvo9GI2e2MaZyo9/lvb+LbLEJZKEQckqRj4P26gmASrZEPStwc+yqy1ShHLA0j6m            1QIDAQAB            -----END PUBLIC KEY-----" | sed 's/   */\n/g' > "/etc/apk/keys/sgerrand.rsa.pub"         && wget -q             "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"             "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"             "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"         && apk add --no-cache             "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"             "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"             "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"                 && rm "/etc/apk/keys/sgerrand.rsa.pub"                 && wget -q ${GCC_LIBS_URL} ${GCC_LIBS_URL}.sig         && mkdir /tmp/gcc         && tar -xf "${GCC_LIBS}" -C /tmp/gcc         && mv /tmp/gcc/usr/lib/libgcc* /tmp/gcc/usr/lib/libstdc++* /usr/glibc-compat/lib         && strip /usr/glibc-compat/lib/libgcc_s.so.* /usr/glibc-compat/lib/libstdc++.so*         && mkdir /tmp/libz         && wget -q "${ZLIB_URL}" "${ZLIB_URL}.sig"         && tar -xf "${ZLIB}" -C /tmp/libz         && mv /tmp/libz/usr/lib/libz.so* /usr/glibc-compat/lib         &&         /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8         && echo "export LANG=en_US.UTF-8" > /etc/profile.d/locale.sh                 && apk del glibc-i18n                 && apk del .build-dependencies         && rm             "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"             "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"             "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"                 && rm -rf /tmp/${GLIBC_VER}.apk /tmp/gcc /tmp/${ZLIB} /tmp/libz /tmp/${GCC_LIBS} /var/cache/apk/*         ;     elif [ -f /etc/debian_version ] ; then         echo "Debian, setting locales"         && apt-get update         && apt-get install -y --no-install-recommends locales         && localedef  -i en_US -f UTF-8 en_US.UTF-8         && rm -rf /var/lib/apt/lists/*         ;     fi' returned a non-zero code: 4
[root@crowd jenkins-jnlp-slave]#

**Comment by yamazakei321** [comment] 2019-09-26 14:49
My env:
centos 7
docker 18.09.9

**Comment by odavid** [comment] 2019-10-24 09:53
Hi @yamazakei321, 
I could not reproduce that issue.
Googling it a bit, `code: 4`, seems to be related to network like proxy, FW, etc...

I am closing this issue, since it seems not related to the code itself.

**Closed as completed by odavid** 2019-10-24 09:53 UTC
